export default {
  content: ["./src/**/*.{html,js,jsx}"],
  theme: {
    screens: {
      xs: "475px",
      sm: "640px",
      md: "850px",
      lg: "1124px",
      xl: "1280px",
      "2xl": "1536px",

      "down-sm": { max: "639px" },
      "down-md": { max: "767px" },
      "down-lg": { max: "1023px" },
      "down-xl": { max: "1279px" },
      "down-2xl": { max: "1535px" },

      "up-sm": { min: "640px" },
      "up-md": { min: "768px" },
      "up-lg": { min: "1024px" },
      "up-xl": { min: "1280px" },
      "up-2xl": { min: "1536px" },
    },
    extend: {
      maxWidth: {
        '8xl': '90rem', 
        '9xl': '100rem',
      },
      colors: {
        btnbackground: "#FF7300",
        hoverbtn: "#ea580c",
        primary: "#005687",
        bluePrimary: "#005687",
        pink: "#FFF1E6",
        secondary: "#64748B",
        searchField: "#F1F5F9",
        white: "#FFFFFF",
        transparentCooking: "#9F9F9F80",
        selectBg: "#D9D9D999",
        recent: "#DADADA99",
        recentBorder: "#AEAEAE",
        paginationButtonBorder: "#737579",
        recommendationBorder: "#82828233",
        recommendedVideo: "#E2E2E2",
        headerInput: "#ECECEC66",
        offBackground: "#E9E9E9",
        offText: "#5A5A5A",
        offBorder: "#D8D8D859",
        lightBrown: "#A6A6A6",
        lightBrowText: "#8B8B8B",
        signText: "#666687",
        signInputBorder: "#DCDCE4",
        description: "#3B73CC",
        largeLight: "#0C3373",
        dashboardPrimary: "#F28327",
        heading: "#0C3373",
      },
      fontFamily: {
        pally: ["Pally", "sans-serif"],
        HelveticaNeue: ['"Helvetica Neue"', "Helvetica", "Arial", "sans-serif"],
        sans: ["Roboto", "sans-serif"],
      },
      fontWeight: {
        medium: "500",
      },
      fontSize: {
        // Existing sizes (keeping for backward compatibility)
        headingsize: ["40px"],
        smallscreenheading: ["20px"],
        "base-bold": ["16px", { lineHeight: "24px", fontWeight: "700" }],
        largeLight: ["32px", { fontWeight: "700" }],
        description: ["18px", { fontWeight: "400" }],
        textheading: ["52px"],
        textsmallheading: ["24px"],
        btntextsize: ["20px"],
        dashboardheadingsize: ["24px"],
        dashboardparasize: ["16px"],

        // New responsive font system
        // Buttons
        "btn-sm": ["14px", { lineHeight: "20px" }],
        "btn-base": ["16px", { lineHeight: "24px" }],
        "btn-lg": ["18px", { lineHeight: "28px" }],
        "btn-xl": ["20px", { lineHeight: "32px" }],

        // Body text
        "body-xs": ["12px", { lineHeight: "18px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "body-base": ["16px", { lineHeight: "24px" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-xl": ["20px", { lineHeight: "32px" }],

        // Headings
        "heading-xs": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "heading-sm": ["20px", { lineHeight: "32px", fontWeight: "600" }],
        "heading-base": ["24px", { lineHeight: "36px", fontWeight: "600" }],
        "heading-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "heading-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "heading-2xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "heading-3xl": ["56px", { lineHeight: "64px", fontWeight: "700" }],
        "heading-4xl": ["72px", { lineHeight: "80px", fontWeight: "700" }],
      },
      // helvetica: ['Helvetica', 'Arial', 'sans-serif'],
      // HelveticaNeue: ['"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
      plusJakarta: ['"Plus Jakarta Sans"', "sans-serif"],
      poppins: ["Poppins", "sans-serif"],
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
      },
    },
  },
  plugins: [],
};
